github.com:
    users:
        Sliman-Baghouri:
            oauth_token: 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
        CtrlFreaks:
            oauth_token: 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
    git_protocol: https
    user: Sliman-Baghouri
    oauth_token: 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
