wallpaper {
    monitor = eDP-1
    path = /home/rodya/Pictures/31.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/rodya/Pictures/31.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/rodya/Pictures/31.png
    fit_mode = cover
}

splash = true
ipc = true
