[pyprland]
plugins = ["scratchpads"]


[scratchpads.term]
animation = ""
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
position = "20% 20%"
size = "55% 55%"
lazy = true 


[scratchpads.mobile]
command = "scrcpy"
class = "mobile-dropdown"
lazy = true 

